"""update db schema for User table to accommodate password hashing

Revision ID: 1108958febca
Revises: 606ad6d5cdf7
Create Date: 2025-02-07 14:38:28.824142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1108958febca'
down_revision = '606ad6d5cdf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_photos_photo_shoot_id_photo_shoots', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_photos_photo_shoot_id_photo_shoots'), 'photo_shoots', ['photo_shoot_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('_password_hash')

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_photos_photo_shoot_id_photo_shoots'), type_='foreignkey')
        batch_op.create_foreign_key('fk_photos_photo_shoot_id_photo_shoots', 'photo_shoots', ['photo_shoot_id'], ['id'])

    # ### end Alembic commands ###
